// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Image analysis AI agent for verifying DSA question work legitimacy.
 *
 * - analyzeImage - A function that handles the image analysis process.
 * - AnalyzeImageInput - The input type for the analyzeImage function.
 * - AnalyzeImageOutput - The return type for the analyzeImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the work done for a DSA question, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  questionDescription: z.string().describe('The description of the DSA question.'),
});
export type AnalyzeImageInput = z.infer<typeof AnalyzeImageInputSchema>;

const AnalyzeImageOutputSchema = z.object({
  isLegitimate: z
    .boolean()
    .describe(
      'Whether the image is a legitimate representation of work done on the DSA question.'
    ),
  reason: z
    .string()
    .describe('The reason for the determination of legitimacy.'),
});
export type AnalyzeImageOutput = z.infer<typeof AnalyzeImageOutputSchema>;

export async function analyzeImage(input: AnalyzeImageInput): Promise<AnalyzeImageOutput> {
  return analyzeImageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeImagePrompt',
  input: {schema: AnalyzeImageInputSchema},
  output: {schema: AnalyzeImageOutputSchema},
  prompt: `You are an AI assistant that analyzes images to determine if they are legitimate representations of work done on a specific DSA question.\n\nYou will receive a photo of what a student claims is their work on a DSA question, along with a description of the question itself.\n\nYour task is to determine if the image is a genuine attempt to solve the question. Consider factors such as:\n- Does the image contain code, diagrams, or notes relevant to the question?\n- Is the content in the image consistent with the type of problem described in the question?\n- Are there any obvious signs that the image is unrelated to the question (e.g., a picture of nature, a random object)?\n\nBased on your analysis, set the 'isLegitimate' field to true if the image appears to be a legitimate attempt to solve the DSA question, and false otherwise. Provide a brief 'reason' explaining your determination.\n\nHere is the DSA question description: {{{questionDescription}}}\nHere is the photo: {{media url=photoDataUri}}\n\nEnsure that your response is concise and directly addresses the legitimacy of the image in relation to the DSA question.\n`,
});

const analyzeImageFlow = ai.defineFlow(
  {
    name: 'analyzeImageFlow',
    inputSchema: AnalyzeImageInputSchema,
    outputSchema: AnalyzeImageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
