export type Question = {
  id: string;
  title: string;
  description: string;
  category: string;
  link: string;
};

export type Category = {
  name: string;
  questions: Question[];
};

const dsaQuestions: Category[] = [
  {
    name: "Step 1: Learn the Basics",
    questions: [
      {
        id: "step-1-1",
        title: "User Input / Output",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/c/c-basic-input-output/",
      },
      {
        id: "step-1-2",
        title: "Data Types",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "#",
      },
      {
        id: "step-1-3",
        title: "If Else statements",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/if-else/if-else-statements/",
      },
      {
        id: "step-1-4",
        title: "Switch Statement",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/switch-case/switch-case-statements/",
      },
      {
        id: "step-1-5",
        title: "What are arrays, strings?",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "#",
      },
      {
        id: "step-1-6",
        title: "For loops",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/for-loop/understanding-for-loop/",
      },
      {
        id: "step-1-7",
        title: "While loops",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/while-loop/while-loops-in-programming/",
      },
      {
        id: "step-1-8",
        title: "Functions (Pass by Reference and Value)",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "#",
      },
      {
        id: "step-1-9",
        title: "Time Complexity [Learn Basics, and then analyse in next Steps]",
        description: "Lec 1: Things to Know in C++/Java/Python or any language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/time-complexity/time-and-space-complexity-strivers-a2z-dsa-course/",
      },
      {
        id: "step-1-10",
        title: "Patterns",
        description: "Lec 2: Build-up Logical Thinking",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/strivers-a2z-dsa-course/must-do-pattern-problems-before-starting-dsa/",
      },
      {
        id: "step-1-11",
        title: "C++ STL",
        description: "Lec 3: Learn STL/Java-Collections or similar thing in your language",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/c/c-stl-tutorial-most-frequent-used-stl-containers/",
      },
      {
        id: "step-1-12",
        title: "Java Collections",
        description: "Lec 3: Learn STL/Java-Collections or similar thing in your language",
        category: "Step 1: Learn the Basics",
        link: "#",
      },
      {
        id: "step-1-13",
        title: "Count Digits",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/count-digits-in-a-number/",
      },
      {
        id: "step-1-14",
        title: "Reverse a Number",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/maths/reverse-digits-of-a-number",
      },
      {
        id: "step-1-15",
        title: "Check Palindrome",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/",
      },
      {
        id: "step-1-16",
        title: "GCD Or HCF",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/find-gcd-of-two-numbers/",
      },
      {
        id: "step-1-17",
        title: "Armstrong Numbers",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/maths/check-if-a-number-is-armstrong-number-or-not/",
      },
      {
        id: "step-1-18",
        title: "Print all Divisors",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/print-all-divisors-of-a-given-number/",
      },
      {
        id: "step-1-19",
        title: "Check for Prime",
        description: "Lec 4: Know Basic Maths",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/",
      },
      {
        id: "step-1-20",
        title: "Understand recursion by print something N times",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/recursion/introduction-to-recursion-understand-recursion-by-printing-something-n-times/",
      },
      {
        id: "step-1-21",
        title: "Print name N times using recursion",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/recursion/print-name-n-times-using-recursion/",
      },
      {
        id: "step-1-22",
        title: "Print 1 to N using recursion",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/recursion/print-1-to-n-using-recursion/",
      },
      {
        id: "step-1-23",
        title: "Print N to 1 using recursion",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/recursion/print-n-to-1-using-recursion/",
      },
      {
        id: "step-1-24",
        title: "Sum of first N numbers",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/sum-of-first-n-natural-numbers/",
      },
      {
        id: "step-1-25",
        title: "Factorial of N numbers",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/factorial-of-a-number-iterative-and-recursive/",
      },
      {
        id: "step-1-26",
        title: "Reverse an array",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/reverse-a-given-array/",
      },
      {
        id: "step-1-27",
        title: "Check if a string is palindrome or not",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/check-if-the-given-string-is-palindrome-or-not/",
      },
      {
        id: "step-1-28",
        title: "Fibonacci Number",
        description: "Lec 5: Learn Basic Recursion",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/arrays/print-fibonacci-series-up-to-nth-term/",
      },
      {
        id: "step-1-29",
        title: "Hashing Theory",
        description: "Lec 6: Learn Basic Hashing",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/hashing/hashing-maps-time-complexity-collisions-division-rule-of-hashing-strivers-a2z-dsa-course/",
      },
      {
        id: "step-1-30",
        title: "Counting frequencies of array elements",
        description: "Lec 6: Learn Basic Hashing",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/data-structure/count-frequency-of-each-element-in-the-array/",
      },
      {
        id: "step-1-31",
        title: "Find the highest/lowest frequency element",
        description: "Lec 6: Learn Basic Hashing",
        category: "Step 1: Learn the Basics",
        link: "https://takeuforward.org/arrays/find-the-highest-lowest-frequency-element/",
      },
    ],
  },
  {
    name: "Step 2: Learn Important Sorting Techniques",
    questions: [
      {
        id: "step-2-1",
        title: "Selection Sort",
        description: "Lec 1: Sorting-I",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/sorting/selection-sort-algorithm/",
      },
      {
        id: "step-2-2",
        title: "Bubble Sort",
        description: "Lec 1: Sorting-I",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/data-structure/bubble-sort-algorithm/",
      },
      {
        id: "step-2-3",
        title: "Insertion Sort",
        description: "Lec 1: Sorting-I",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/data-structure/insertion-sort-algorithm/",
      },
      {
        id: "step-2-4",
        title: "Merge Sort",
        description: "Lec 2: Sorting-II",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/data-structure/merge-sort-algorithm/",
      },
      {
        id: "step-2-5",
        title: "Recursive Bubble Sort",
        description: "Lec 2: Sorting-II",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/arrays/recursive-bubble-sort-algorithm/",
      },
      {
        id: "step-2-6",
        title: "Recursive Insertion Sort",
        description: "Lec 2: Sorting-II",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/arrays/recursive-insertion-sort-algorithm/",
      },
      {
        id: "step-2-7",
        title: "Quick Sort",
        description: "Lec 2: Sorting-II",
        category: "Step 2: Learn Important Sorting Techniques",
        link: "https://takeuforward.org/data-structure/quick-sort-algorithm/",
      },
    ],
  },
  {
    name: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
    questions: [
      {
        id: "step-3-1",
        title: "Largest Element in an Array",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/",
      },
      {
        id: "step-3-2",
        title: "Second Largest Element in an Array without sorting",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element-in-an-array/",
      },
      {
        id: "step-3-3",
        title: "Check if the array is sorted",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/check-if-an-array-is-sorted/",
      },
      {
        id: "step-3-4",
        title: "Remove duplicates from Sorted array",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/",
      },
      {
        id: "step-3-5",
        title: "Left Rotate an array by one place",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/left-rotate-the-array-by-one/",
      },
      {
        id: "step-3-6",
        title: "Left rotate an array by D places",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/rotate-array-by-k-elements/",
      },
      {
        id: "step-3-7",
        title: "Move Zeros to end",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/",
      },
      {
        id: "step-3-8",
        title: "Linear Search",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/linear-search-in-c/",
      },
      {
        id: "step-3-9",
        title: "Find the Union",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/union-of-two-sorted-arrays/",
      },
      {
        id: "step-3-10",
        title: "Find missing number in an array",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/arrays/find-the-missing-number-in-an-array/",
      },
      {
        id: "step-3-11",
        title: "Maximum Consecutive Ones",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/",
      },
      {
        id: "step-3-12",
        title: "Find the number that appears once, and other numbers twice.",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/arrays/find-the-number-that-appears-once-and-the-other-numbers-twice/",
      },
      {
        id: "step-3-13",
        title: "Longest subarray with given sum K(positives)",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/longest-subarray-with-given-sum-k/",
      },
      {
        id: "step-3-14",
        title: "Longest subarray with sum K (Positives + Negatives)",
        description: "Lec 1: Easy",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/arrays/longest-subarray-with-sum-k-postives-and-negatives/",
      },
      {
        id: "step-3-15",
        title: "2Sum Problem",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/",
      },
      {
        id: "step-3-16",
        title: "Sort an array of 0's 1's and 2's",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/",
      },
      {
        id: "step-3-17",
        title: "Majority Element (>n/2 times)",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/",
      },
      {
        id: "step-3-18",
        title: "Kadane's Algorithm, maximum subarray sum",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",
      },
      {
        id: "step-3-19",
        title: "Print subarray with maximum subarray sum (extended version of above problem)",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum-in-an-array/",
      },
      {
        id: "step-3-20",
        title: "Stock Buy and Sell",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/stock-buy-and-sell/",
      },
      {
        id: "step-3-21",
        title: "Rearrange the array in alternating positive and negative items",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/arrays/rearrange-array-elements-by-sign/",
      },
      {
        id: "step-3-22",
        title: "Next Permutation",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/",
      },
      {
        id: "step-3-23",
        title: "Leaders in an Array problem",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/leaders-in-an-array/",
      },
      {
        id: "step-3-24",
        title: "Longest Consecutive Sequence in an Array",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/",
      },
      {
        id: "step-3-25",
        title: "Set Matrix Zeros",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/set-matrix-zero/",
      },
      {
        id: "step-3-26",
        title: "Rotate Matrix by 90 degrees",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/rotate-image-by-90-degree/",
      },
      {
        id: "step-3-27",
        title: "Print the matrix in spiral manner",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/spiral-traversal-of-matrix/",
      },
      {
        id: "step-3-28",
        title: "Count subarrays with given sum",
        description: "Lec 2: Medium",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/arrays/count-subarray-sum-equals-k/",
      },
      {
        id: "step-3-29",
        title: "Pascal's Triangle",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/program-to-generate-pascals-triangle/",
      },
      {
        id: "step-3-30",
        title: "Majority Element (n/3 times)",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/majority-elementsn-3-times-find-the-elements-that-appears-more-than-n-3-times-in-the-array/",
      },
      {
        id: "step-3-31",
        title: "3-Sum Problem",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/",
      },
      {
        id: "step-3-32",
        title: "4-Sum Problem",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/4-sum-find-quads-that-add-up-to-a-target-value/",
      },
      {
        id: "step-3-33",
        title: "Largest Subarray with 0 Sum",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/length-of-the-longest-subarray-with-zero-sum/",
      },
      {
        id: "step-3-34",
        title: "Count number of subarrays with given xor K",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/count-the-number-of-subarrays-with-given-xor-k/",
      },
      {
        id: "step-3-35",
        title: "Merge Overlapping Subintervals",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/",
      },
      {
        id: "step-3-36",
        title: "Merge two sorted arrays without extra space",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/",
      },
      {
        id: "step-3-37",
        title: "Find the repeating and missing number",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/",
      },
      {
        id: "step-3-38",
        title: "Count Inversions",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/count-inversions-in-an-array/",
      },
      {
        id: "step-3-39",
        title: "Reverse Pairs",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/count-reverse-pairs/",
      },
      {
        id: "step-3-40",
        title: "Maximum Product Subarray",
        description: "Lec 3: Hard",
        category: "Step 3: Solve Problems on Arrays [Easy -> Medium -> Hard]",
        link: "https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/",
      },
    ],
  },
  {
    name: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
    questions: [
      {
        id: "step-4-1",
        title: "Binary Search to find X in sorted array",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/binary-search-explained/",
      },
      {
        id: "step-4-2",
        title: "Implement Lower Bound",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/implement-lower-bound-bs-2/",
      },
      {
        id: "step-4-3",
        title: "Implement Upper Bound",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/implement-upper-bound/",
      },
      {
        id: "step-4-4",
        title: "Search Insert Position",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/search-insert-position/",
      },
      {
        id: "step-4-5",
        title: "Floor/Ceil in Sorted Array",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/floor-and-ceil-in-sorted-array/",
      },
      {
        id: "step-4-6",
        title: "Find the first or last occurrence of a given number in a sorted array",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/last-occurrence-in-a-sorted-array/",
      },
      {
        id: "step-4-7",
        title: "Count occurrences of a number in a sorted array with duplicates",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/count-occurrences-in-sorted-array/",
      },
      {
        id: "step-4-8",
        title: "Search in Rotated Sorted Array I",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/",
      },
      {
        id: "step-4-9",
        title: "Search in Rotated Sorted Array II",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/search-element-in-rotated-sorted-array-ii/",
      },
      {
        id: "step-4-10",
        title: "Find minimum in Rotated Sorted Array",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/minimum-in-rotated-sorted-array/",
      },
      {
        id: "step-4-11",
        title: "Find out how many times has an array been rotated",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/find-out-how-many-times-the-array-has-been-rotated/",
      },
      {
        id: "step-4-12",
        title: "Single element in a Sorted Array",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/search-single-element-in-a-sorted-array/",
      },
      {
        id: "step-4-13",
        title: "Find peak element",
        description: "Lec 1: BS on 1D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/peak-element-in-array/",
      },
      {
        id: "step-4-14",
        title: "Find square root of a number in log n",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/binary-search/finding-sqrt-of-a-number-using-binary-search/",
      },
      {
        id: "step-4-15",
        title: "Find the Nth root of a number using binary search",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/nth-root-of-a-number-using-binary-search/",
      },
      {
        id: "step-4-16",
        title: "Koko Eating Bananas",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/binary-search/koko-eating-bananas/",
      },
      {
        id: "step-4-17",
        title: "Minimum days to make M bouquets",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/minimum-days-to-make-m-bouquets/",
      },
      {
        id: "step-4-18",
        title: "Find the smallest Divisor",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/find-the-smallest-divisor-given-a-threshold/",
      },
      {
        id: "step-4-19",
        title: "Capacity to Ship Packages within D Days",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/capacity-to-ship-packages-within-d-days/",
      },
      {
        id: "step-4-20",
        title: "Aggressive Cows",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/binary-search/aggressive-cows-problem/",
      },
      {
        id: "step-4-21",
        title: "Book Allocation Problem",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/data-structure/allocate-minimum-number-of-pages/",
      },
      {
        id: "step-4-22",
        title: "Split array - Largest Sum",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/split-array-largest-sum/",
      },
      {
        id: "step-4-23",
        title: "Kth Missing Positive Number",
        description: "Lec 2: BS on Answers",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://takeuforward.org/arrays/kth-missing-positive-number/",
      },
      {
        id: "step-4-24",
        title: "Row with maximum number of ones",
        description: "Lec 3: BS on 2D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/arrays/row-with-maximum-number-of-ones/",
      },
      {
        id: "step-4-25",
        title: "Search in a 2D Matrix",
        description: "Lec 3: BS on 2D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/arrays/search-element-in-a-matrix/",
      },
      {
        id: "step-4-26",
        title: "Search in a 2D Matrix II",
        description: "Lec 3: BS on 2D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/arrays/search-element-in-a-matrix-ii/",
      },
      {
        id: "step-4-27",
        title: "Find a peak element in 2D Matrix",
        description: "Lec 3: BS on 2D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/arrays/find-peak-element-in-2d-matrix/",
      },
      {
        id: "step-4-28",
        title: "Median in a row-wise sorted matrix",
        description: "Lec 3: BS on 2D Arrays",
        category: "Step 4: Binary Search [1D, 2D Arrays, Search Space]",
        link: "https://www.google.com/search?q=https://takeuforward.org/arrays/median-in-row-wise-sorted-matrix/",
      },
    ],
  },
];


export const allQuestions: Question[] = dsaQuestions.flatMap(category => category.questions);

export const getQuestionById = (id: string): Question | undefined => allQuestions.find(q => q.id === id);

export default dsaQuestions;
